// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlY2AVQ5aSWb59m4eY5-zjzf_ql1fRMDY',
    appId: '1:646644569125:android:69c278a812e66bc29c9bcc',
    messagingSenderId: '646644569125',
    projectId: 'mood-journal-26002',
    authDomain: 'mood-journal-26002.firebaseapp.com',
    storageBucket: 'mood-journal-26002.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlY2AVQ5aSWb59m4eY5-zjzf_ql1fRMDY',
    appId: '1:646644569125:android:69c278a812e66bc29c9bcc',
    messagingSenderId: '646644569125',
    projectId: 'mood-journal-26002',
    storageBucket: 'mood-journal-26002.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlY2AVQ5aSWb59m4eY5-zjzf_ql1fRMDY',
    appId: '1:646644569125:android:69c278a812e66bc29c9bcc',
    messagingSenderId: '646644569125',
    projectId: 'mood-journal-26002',
    storageBucket: 'mood-journal-26002.firebasestorage.app',
    iosBundleId: 'com.example.moodjournal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlY2AVQ5aSWb59m4eY5-zjzf_ql1fRMDY',
    appId: '1:646644569125:android:69c278a812e66bc29c9bcc',
    messagingSenderId: '646644569125',
    projectId: 'mood-journal-26002',
    storageBucket: 'mood-journal-26002.firebasestorage.app',
    iosBundleId: 'com.example.moodjournal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlY2AVQ5aSWb59m4eY5-zjzf_ql1fRMDY',
    appId: '1:646644569125:android:69c278a812e66bc29c9bcc',
    messagingSenderId: '646644569125',
    projectId: 'mood-journal-26002',
    authDomain: 'mood-journal-26002.firebaseapp.com',
    storageBucket: 'mood-journal-26002.firebasestorage.app',
  );
}
