// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzjpIE7ersInzWFMWLX3rs5UrcLSqSNJw',
    appId: '1:370831177284:web:91d622963826e94d02ee11',
    messagingSenderId: '370831177284',
    projectId: 'dailyplanner-ceb29',
    authDomain: 'dailyplanner-ceb29.firebaseapp.com',
    storageBucket: 'dailyplanner-ceb29.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDUYuDnI3uai6zEqN5Dx6ZIlVVVilgETg',
    appId: '1:370831177284:android:218ca133c388fea602ee11',
    messagingSenderId: '370831177284',
    projectId: 'dailyplanner-ceb29',
    storageBucket: 'dailyplanner-ceb29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyFeoa00ZsXVWxIt-4Z3zFjMNyKhmXOz8',
    appId: '1:370831177284:ios:7a608d05d9b7655b02ee11',
    messagingSenderId: '370831177284',
    projectId: 'dailyplanner-ceb29',
    storageBucket: 'dailyplanner-ceb29.firebasestorage.app',
    iosBundleId: 'com.example.dailyplanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyFeoa00ZsXVWxIt-4Z3zFjMNyKhmXOz8',
    appId: '1:370831177284:ios:7a608d05d9b7655b02ee11',
    messagingSenderId: '370831177284',
    projectId: 'dailyplanner-ceb29',
    storageBucket: 'dailyplanner-ceb29.firebasestorage.app',
    iosBundleId: 'com.example.dailyplanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzjpIE7ersInzWFMWLX3rs5UrcLSqSNJw',
    appId: '1:370831177284:web:d7c207607980043702ee11',
    messagingSenderId: '370831177284',
    projectId: 'dailyplanner-ceb29',
    authDomain: 'dailyplanner-ceb29.firebaseapp.com',
    storageBucket: 'dailyplanner-ceb29.firebasestorage.app',
  );
}
